In [1]:
print("hello world")

hello world


In [3]:
def processNumbers(num1,num2):
    resultAdd = num1 + num2
    resultMult = num1 * num2
    return resultAdd, resultMult

num1 = int(input("Enter a number 1: "))
num2 = int(input("Enter a number 2: "))
resultAdd, resultMult = processNumbers(num1,num2)
print("Addition: ", resultAdd)
print("Multiplication: ", resultMult)



Addition:  5
Multiplication:  6


In [12]:
#assignment 1: sum of elements in a list 
#write a functio sum_of_list(lst) that takes a list of numbers as input and returns the sum of the elements in the list
lst = input("Enter a list of numbers separated by space: ")
lst = lst.split()
for i in range(0, len(lst)):
    lst[i] = int(lst[i])
def sum_of_list(lst):
    sum = 0
    for i in lst:
        sum += i
    return sum
print(sum_of_list(lst))



10


In [18]:
#Assignment 2: Count the Frequency of Elements in a list 
#Write a function count_frequency(lst) that takes a list  as input and returns a dictionary where the keys are the elements of the list and the values are the number of times each element appears
lst = input("Enter a list of numbers separated by space: ")
lst = lst.split()
for i in range(0, len(lst)):
    lst[i] = int(lst[i])
def count_frequency(lst):
    frequency = {}
    for i in lst:
        if i in frequency:
            frequency[i] += 1
        else:
            frequency[i] = 1
    return frequency
print(count_frequency(lst))


{1: 2, 2: 1, 3: 2}


In [19]:
#Assignment 3: Return Sum and Product fo Tuple Elements 
#Write a function sum_and_product(tpl) that takes a tuple of numbers as input and returns the tuple containing the sum and product of the elements.
tpl = input("Enter a tuple of numbers separated by space: ")
tpl = tpl.split()
for i in range(0, len(tpl)):
    tpl[i] = int(tpl[i])
def sum_and_product(tpl):
    sum = 0
    product = 1
    for i in tpl:
        sum += i
        product *= i
    return sum, product
print(sum_and_product(tpl))


(6, 6)


In [26]:
#default arguments
def processNumbers(num1,num2=5):
    resultAdd = num1 + num2
    resultMult = num1 * num2
    return resultAdd, resultMult

num1 = int(input("Enter a number 1: "))
num2 = int(input("Enter a number 2: "))
#resultAdd, resultMult = processNumbers(num1)
result= processNumbers(num1)
print(result)   
print(type(result))




(7, 10)
<class 'tuple'>


In [28]:
#default arguments
def processNumbers(num1,num2=5):
    resultAdd = num1 + num2
    resultMult = num1 * num2
    return resultAdd, resultMult

num1 = int(input("Enter a number 1: "))
num2 = int(input("Enter a number 2: "))
# resultAdd, resultMult = processNumbers(num1,num2)
# print("Addition: ", resultAdd)
# print("Multiplication: ", resultMult)

result= processNumbers(num1,num2)
print(result)   
print(type(result))


(4, 4)
<class 'tuple'>


In [32]:
#Keyword arguments / Name arguments
def name_function(num1,num2,num3):
    print(num1)
    print(num2)
    print(num3)

name_function(1,2,3)
print()
name_function(num3=3,num1=1,num2=2)

1
2
3

1
2
3


In [34]:
#Default Arguments 
def greet(name, Message="Hello"):
    print(f"{Message} {name}!")

#With default argument
greet("Alice")
greet("Bob", "Hi")
greet(name="Alice", Message="Good Morning")
greet(Message="Hi", name="Bob")
greet("Hi", "Alice")

Hello Alice!
Hi Bob!
Good Morning Alice!
Hi Bob!
Alice Hi!


In [60]:
#assignment:
# Given a dictionary, of students and their favourite colours:
# people = {Vinay: "Blue", Ram: "Yellow", Vinod: "Purple", Radha: "Pink"}
# Find out how many students are in the list
# Change Ram's favourite colour 
# Remove "Vinod" and her favourite colour
# Sort and print students and their favourite colours alphabetically by name_function
#give output dictionary only

people = {"Vinay": "Blue", "Ram": "Yellow", "Vinod": "Purple", "Radha": "Pink"}
#studens are in a list
print(len(people))
people["Ram"] = "Black"
#del people["Vinod"] 
people.pop("Vinod")
sorted_people = sorted(people.items())
print(type(sorted_people))

# for name, color in sorted_people:
#     print(f"{name}: {color}")

print(sorted_people)
print(dict(sorted_people))


4
<class 'list'>
[('Radha', 'Pink'), ('Ram', 'Black'), ('Vinay', 'Blue')]
{'Radha': 'Pink', 'Ram': 'Black', 'Vinay': 'Blue'}


In [4]:
#voting system for favorite movies 
#implement a function manage_votes() that manages votes for a  list movies 
#Dictionary:
#Key:movie name(string)
#Value:Number of votes(integer)

# Implement the following operations:
# Add a new movie: Add a new movie to the voting list with 0 initial votes.
# Vote for a movie: Increment the vote count for a specific movie 
# Remove a movie: Remove a movie from the voting list
# Display voting results: Display the current vote count for each movie.
# Find the top movie: Find and return the movie with the highest number of votes.

def manage_votes():
    votes = {}
    while True:
        print("1. Add a new movie")
        print("2. Vote for a movie")
        print("3. Remove a movie")
        print("4. Display voting results")
        print("5. Find the top movie")
        print("6. Exit")
        choice = int(input("Enter your choice: "))
        if choice == 1:
            movie = input("Enter the name of the movie: ")
            votes[movie] = 0
        elif choice == 2:
            movie = input("Enter the name of the movie: ")
            if movie in votes:
                votes[movie] += 1
            else:
                print("Movie not found")
        elif choice == 3:
            movie = input("Enter the name of the movie: ")
            if movie in votes:
                del votes[movie]
            else:
                print("Movie not found")
        elif choice == 4:
            for movie, vote in votes.items():
                print(f"{movie}: {vote}")
        elif choice == 5:
            top_movie = max(votes, key=votes.get)
            print(f"Top movie: {top_movie}")
        elif choice == 6:
            break
        else:
            print("Invalid choice")

manage_votes()

1. Add a new movie
2. Vote for a movie
3. Remove a movie
4. Display voting results
5. Find the top movie
6. Exit


ValueError: invalid literal for int() with base 10: ''

In [39]:
# Global and Local Summation 
# Objective: Create a program that calculates the sum of numbers using both global and local variables.

# Tasks:
# 1.Declare a global variable to store the sum of numbers.
# 2.write a function that accepts a list of numbers as input and calculates the sum using a local variable.
# 3.Update th global sum variable with the local sum calculated in the function
# 4.print the global sum before and after calling the function

# Challages:
# 1.Implement another function that resets the global sum to zero and compares the results


#Global and Local Summation
global_sum = 0
def calculate_sum(numbers):
    local_sum = 0
    for number in numbers:
        local_sum += number
    return local_sum

numbers = [1, 2, 3, 4, 5]
global_sum = calculate_sum(numbers)
print(global_sum)

def reset_sum():
    global global_sum
    global_sum = 0
reset_sum()
print(global_sum)






15


NameError: name 'local_sum' is not defined

In [5]:
def find_string_length(strString):
    return len(strString)

str_len=find_string_length("tables")
print(str_len)

6


In [7]:
str='tables'
str_len=lambda str: len(str)
print(str_len(str))

6


In [11]:
#Can accept multiple variables 
def addNumbers(iNum1,iNum2):
    return iNum1+iNum2

result=addNumbers(2,3)
print(result)

print((lambda a,b: a+b)(2,3))

5
5


In [15]:
#passing lambda function as an argument
cube = lambda x: x**3
def apply_function(f, x):
    return f(x)

print(apply_function(cube, 3))



27


In [18]:
def my_lambda_function(func_name,lstNum):
    lstresult = []
    for item in lstNums:
        new_item = func_name(item)
        lstresult.append(new_item)
    return lstresult

lstNums = [1,2,3,4,5,6]
lstcube = my_lambda_function(lambda x: x**3, lstNums)   
print(lstcube)


[1, 8, 27, 64, 125, 216]


In [24]:
#assignment 1: Multiply List Elements by a Constant 
# use a lambda funciton to multiply each element in a list by a constant value. 
# Given a list [2,3,4,5]. Multiply each element by 3 
# Expected output: [6,9,12,15]

def my_lambda_function(func_name,lstNums):
    lstresult = []
    for item in lstNums:
        new_item = func_name(item)
        lstresult.append(new_item)
    return lstresult

lstNums = [2,3,4,5]
lstcube = my_lambda_function(lambda x: x*3, lstNums)
print(lstcube)



[6, 9, 12, 15]


In [29]:
#Assignment 2: Multipy List of Elements by a Constant 
# Use a lambda funciton to multiply each element in a list by a constant balue
# Given a list [2,3,4,5]. Multiply each element by 3
# Expected output: [6,9,12,15]
# using map function

lstNums = [6,3,4,5]
lstcube = list(map(lambda x: x*3, lstNums))
print(lstcube)


[18, 9, 12, 15]


In [36]:
#Conditional lambda funciton
# Objective: Create a program that uses a lambda function to check if a number is positive negative, or zero 

# Tasks 
# 1.Input: List of integers,E.g. Numbers = [10,-5,0,7,-3,4,-2]
# 2.Logic: Use the map() function with a lambda function to return "Positive", "Negative", or "Zero" based on the value of each integers
# 3.Output: Display the resulting list of strings 
# E.g.['Positive','Negative','Zero','Positive','Negative','Positive','Negative']

numbers = [10, -5, 0, 7, -3, 4, -2] 
result = list(map(lambda x: "Positive" if x > 0 else "Negative" if x < 0 else "Zero", numbers))
print(result)

['Positive', 'Negative', 'Zero', 'Positive', 'Negative', 'Positive', 'Negative']


In [37]:
#recursion
def recursive_sum(numbers):
    print(numbers)

    if not numbers:
        return 0
    else:
        return numbers[0] + recursive_sum(numbers[1:])
    
numbers = [1, 2, 3, 4, 5]
result = recursive_sum(numbers)
print("The sum is: ", result)

[1, 2, 3, 4, 5]
[2, 3, 4, 5]
[3, 4, 5]
[4, 5]
[5]
[]
The sum is:  15


In [1]:
print("hello")

hello


# 07/10/2024

### File Handling

In [6]:
# function to write a data in a text file
def write_data_to_file(filename, data):
    with open(filename, "w") as file:
        file.write(data)
    print(f"Data written to {filename} successfully")

filename="example.txt"

write_data_to_file(filename, "Hello, World!\nThis is the first line of the file.\n")

Data written to example.txt successfully


In [9]:
# Function to read data from a text file
def read_data_from_file(filename):
    try: 
        with open(filename, "r") as file:
            content = file.read()
            print(f"contents of {filename}:\n{content}")
    except FileNotFoundError:
        print(f"File {filename} not found")
            
filename="example.txt"
read_data_from_file(filename)


contents of example.txt:
Hello, World!
This is the first line of the file.



In [10]:
# Function to append data to a text file
def append_data_to_file(filename, data):
    with open(filename, "a") as file:
        file.write(data)
    print(f"Data appended to {filename} successfully")

filename="example.txt"
append_data_to_file(filename, "This is the second line of the file.\n")


Data appended to example.txt successfully


In [11]:
import csv

# Data to write

data = [
    ["Name", "Age", "Grade"],
    ["Alice", 25, "A"],
    ["Bob", 30, "B"],
    ["Charlie", 35, "C"]
]
# Open the file in write mode
filename = "example.csv"


with open(filename, mode="w", newline="", encoding="utf-8") as file:
    writer = csv.writer(file)
    writer.writerows(data)
print(f"Data written to {filename} successfully")


#Open the file in read mode
filename = "example.csv"
with open(filename, mode="r", newline="", encoding="utf-8") as file:
    reader = csv.reader(file)
    #read the header (first row)
    header = next(reader)
    print(f"Header: {header}")

    #read the remaining rows
    for row in reader:
        print(row)


Data written to example.csv successfully
Header: ['Name', 'Age', 'Grade']
['Alice', '25', 'A']
['Bob', '30', 'B']
['Charlie', '35', 'C']


In [7]:
#assignment 1 
# Read a.txt file and print contents on console
filename = "example.txt"
with open(filename, "r") as file:
    content = file.read()
    print(content)


Hello, World!
This is the first line of the file.
This is the second line of the file.



In [12]:
#assignment 2
# Write a program to read a.csv file and print the contents on the console
filename = "example.csv"
with open(filename, "r", newline="", encoding="utf-8") as file:
    reader = csv.reader(file)
    for row in reader:
        print(row)



['Name', 'Age', 'Grade']
['Alice', '25', 'A']
['Bob', '30', 'B']
['Charlie', '35', 'C']


In [2]:
import csv
# Assignment 3
#Accept Name,Age,Marks of a student form a user and store in a csv file.

filename = "students.csv"
data = []
data.append(["Name", "Age", "Marks"])
while True:
    name = input("Enter the name of the student: ")
    age = int(input("Enter the age of the student: "))
    marks = float(input("Enter the marks of the student: "))
    data.append([name, age, marks])
    choice = input("Do you want to add another student? (y/n): ")
    if choice.lower() != "y":
        break
with open(filename, mode="w", newline="", encoding="utf-8") as file:
    writer = csv.writer(file)
    writer.writerows(data)
print(f"Data written to {filename} successfully")


Data written to students.csv successfully


In [9]:
def write_data_to_file(filename: str, my_dict: dict):
    with open(filename, "a") as file:
        for key, value in my_dict.items():
            file.write(f"{key}: {value}\n")
    print(f"Data written to {filename} successfully")

In [11]:
#Assignment 4: Store dictionary contents to a file 
# Accept student details form the user (Name, Roll NO, Science, Maths, English marks), store in a dictinoary. 
# Calculate average and add to dictionary.
# Open file in append mode. 
# Add dictionary contents to the file.

filename = "students.txt"
student = {}
student["Name"] = input("Enter the name of the student: ")
student["Roll No"] = input("Enter the roll number of the student: ")
student["Science"] = float(input("Enter the science marks of the student: "))
student["Maths"] = float(input("Enter the maths marks of the student: "))
student["English"] = float(input("Enter the english marks of the student: "))
student["Average"] = round((student["Science"] + student["Maths"] + student["English"]) / 3, 2)
#student["Average"] = (student["Science"] + student["Maths"] + student["English"]) / 3

def write_data_to_file(filename: str, my_dict: dict):
    with open(filename, "a") as file:
        for key, value in my_dict.items():
            file.write(f"{key}: {value}\n")
    print(f"Data written to {filename} successfully")

write_data_to_file(filename, student)




Data written to students.txt successfully


In [19]:
data = {'Name': 'Alice', 'Age': 25, 'City': 'New York'}
filename = "students.csv"
with open(filename, mode="w", newline="") as file:
    # Get the keys of the dictionary as fieldnames for the CSV header
    fieldnames = data.keys()
    # Create a DictWriter object, passing the fieldnames as the fieldnames
    writer = csv.DictWriter(file, fieldnames=fieldnames)
    # Write the header 
    writer.writeheader()
    # Write the single row of data
    
    writer.writerows(data)
print(f"Data written to {filename} successfully")

AttributeError: 'str' object has no attribute 'keys'

In [17]:
#Assignment 4: Store dictionary contents to a csv
# Accept student details form the user (Name, Roll NO, Science, Maths, English marks), store in a dictionary in dictionary.
# Calculate average and add to dictionary.
# Open file in append mode. 
# Add  dictionaries to file.
filename = "students.csv"
students = []

def add_student():
    student = {}
    student["Name"] = input("Enter the name of the student: ")
    student["Roll No"] = input("Enter the roll number of the student: ")
    student["Science"] = float(input("Enter the science marks of the student: "))
    student["Maths"] = float(input("Enter the maths marks of the student: "))
    student["English"] = float(input("Enter the english marks of the student: "))
    student["Average"] = round((student["Science"] + student["Maths"] + student["English"]) / 3, 2)
    students.append(student)

def write_data_to_file(filename: str, my_list: list):
    with open(filename, mode="a", newline="") as file:
        fieldnames = my_list[0].keys()
        writer = csv.DictWriter(file, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(my_list)
    print(f"Data written to {filename} successfully")

while True:
    print("1. Add a new student")
    print("2. Save and exit")
    choice = input("Enter your choice: ")
    if choice == "1":
        add_student()
    elif choice == "2":
        write_data_to_file(filename, students)
        break
    else:
        print("Invalid choice. Please try again.")


        



1. Add a new student
2. Save and exit
1. Add a new student
2. Save and exit
Data written to students.csv successfully


In [6]:
#Assignment 1: Write and read a list of numbers 
# create a list of random numbers 
# Write the list to a file numbers.txt with each number on a new line.
# Read the file and store the numbers in a new list.
# Calculate and display the sum of the numbers.

list_numbers = []
print("how many numbers do you want to enter: ")
n = int(input())
for i in range(0, n):
    print("Enter number: ")
    num = int(input())
    list_numbers.append(num)
    
#list_numbers = [1,2,3,4,5,6,7,8,9,10]
filename = "numbers.txt"
with open(filename, "w") as file:
    for number in list_numbers:
        file.write(f"{number}\n")
print(f"Data written to {filename} successfully")

with open(filename, "r") as file:
    numbers = [int(line.strip()) for line in file]
print(f"Numbers read from {filename}: {numbers}")

sum = 0
for number in numbers:
    sum += number
print(f"Sum of the numbers: {sum}")



how many numbers do you want to enter: 
Enter number: 
Enter number: 
Enter number: 
Enter number: 
Enter number: 
Enter number: 
Data written to numbers.txt successfully
Numbers read from numbers.txt: [1, 2, 3, 4, 5, 6]
Sum of the numbers: 21


In [16]:
# Assignment 2: Sorting Data from a file 
# Create a csv file which holds a list of words. 
# Read data form thr file into a list 
# sort the list in ascending order 
# write the sorted data back to the file, also print on console

import csv

words = ["Red", "Blue", "Green", "Yellow", "Orange", "Purple"]
filename = "words.csv"
with open(filename, "w", newline="") as file:
    writer = csv.writer(file)
    writer.writerow(words)
print(f"Data written to {filename} successfully")

print(words)

with open(filename, "r", newline="") as file:
    reader = csv.reader(file)
    for row in reader:
        words = row
words.sort()

with open(filename, "w", newline="") as file:
    writer = csv.writer(file)
    writer.writerow(words)
print(f"Data written to {filename} successfully")

print(words)



Data written to words.csv successfully
['Red', 'Blue', 'Green', 'Yellow', 'Orange', 'Purple']
Data written to words.csv successfully
['Blue', 'Green', 'Orange', 'Purple', 'Red', 'Yellow']


In [17]:
#Exception Handling

#try block
try:
    #code that may raise an exception
    x = 1 / 0
except ZeroDivisionError:
    #code to handle the exception
    print("Cannot divide by zero")
    

Cannot divide by zero


In [19]:
#try block with multiple exceptions
try:
    #code that may raise an exception
    x = 1 / 0
except ZeroDivisionError:
    #code to handle the exception
    print("Cannot divide by zero")
except:
    #code to handle any other exception
    print("An error occurred")
    

Cannot divide by zero


In [21]:
print("Demo 1: Basic try-except block")
try:
    x = int("not a number")
except ValueError:
    print("Caught a ValueError: Invalid literal for int()")

Demo 1: Basic try-except block
Caught a ValueError: Invalid literal for int()


In [22]:
#Multiple except blocks (handling different exceptions separately)
print("\nDemo 2: Multiple except blocks")
try:
    y=10 / 0    
except ValueError:
    print("Caught a ValueError")
except ZeroDivisionError:
    print("Caught a ZeroDivisionError")
except:
    print("Caught an exception")
    


Demo 2: Multiple except blocks
Caught a ZeroDivisionError


In [25]:
print("\nDemo 2: Multiple except blocks")
try:
    x=int(input("Enter a number: "))
    y=x / 0    
    print(y)
except ValueError:
    print("Caught a ValueError")
except ZeroDivisionError:
    print("Caught a ZeroDivisionError")
    


Demo 2: Multiple except blocks
Caught a ZeroDivisionError


In [27]:
print("Demo 3: Try-except-finally block")
try:
    z=10 / 5
except ZeroDivisionError:
    print("Caught a ZeroDivisionError")
finally:
    print("This block will always execute, regardless of an exception occurred ")

Demo 3: Try-except-finally block
This block will always execute, regardless of an exception occurred 


In [29]:
print("Demo 4: Try-except-else-finally  block")
try:
    result=10 / 0
except ZeroDivisionError:
    print("Caught a ZeroDivisionError")
else:
    print(f"Division Successful: result is {result}")
finally:
    print("This block will always execute, regardless of an exception occurred ")

Demo 4: Try-except-else-finally  block
Caught a ZeroDivisionError
This block will always execute, regardless of an exception occurred 


In [30]:
# Raising an exception using the raise statement

print("Demo 5: Raising an exception")
try:
    age = -1
    if age < 0:
        raise ValueError("Age cannot be negative")
except ValueError as e:
    print(f"Raised and caught an exception: {e}")

Demo 5: Raising an exception
Raised and caught an exception: Age cannot be negative


In [31]:
# Raising an exception using the raise statement

print("Demo 5: Raising an exception")
try:
    age = -1
    amount = -1000
    if age < 0:
        raise ValueError("Age cannot be negative")
    if amount < 0:
        raise ValueError("Amount cannot be negative")
    
except ValueError as e:
    print(f"Raised and caught an exception: {e}")

Demo 5: Raising an exception
Raised and caught an exception: Age cannot be negative


In [38]:
# #Assignment 4: Define the functions which handle exceptions 
# Function 1: get_integer_input-Accepts an integer and prints it 
# Exception to handle:
#     ValueError exceptions 

 



def get_integer_input():
    try:
        num = int(input("Enter an integer: "))
        print(f"Entered integer: {num}")
    except ValueError:
        print("Invalid input. Please enter an integer")

# Function 2: get_element_from_list-Attempts to return element at specified index from list. 
# Exception to handle:
#     IndexError : if the index is out of bounds
#     TypeError: if the index is not an integer
#     Use else : Print the element if no exceptions occur 
#     finally blocks: to indicate operation completion

def get_element_from_list(lst, index):
    try:
        element = lst[index]
    except IndexError:
        print("Index out of bounds")
    except TypeError:
        print("Index must be an integer")
    else:
        print(f"Element at index {index}: {element}")
    finally:
        print("Operation completed")



# Function 3: divide_numbers(a,b)-Raises ZeroDivisionError if b is zero.
#     Exception to handle: 
#     ZeroDivisionError-Custom message in body

def divide_numbers(a, b):
    try:
        if b == 0:
            raise ZeroDivisionError("Cannot divide by zero")
        result = a / b
        print(f"Result of division: {result}")
    except ZeroDivisionError as e:
        print(e)

get_integer_input()
print("----------------")
list = [1, 2, 3, 4, 5]
get_element_from_list(list, 2)
print()
get_element_from_list(list, 10)
print()
get_element_from_list(list, "a")
print("----------------")
divide_numbers(10, 0)
print()
divide_numbers(10, 2)


Entered integer: 55
----------------
Element at index 2: 3
Operation completed

Index out of bounds
Operation completed

Index must be an integer
Operation completed
----------------
Cannot divide by zero

Result of division: 5.0


In [4]:
class phonebook:
    strName = ""
    strPhone = ""
    strAddress = ""

    def setValue(self, name, phone, address):
        self.strName = name
        self.strPhone = phone
        self.strAddress = address

    def display_phonebook(self):
        print("Name: ", self.strName)
        print("Phone: ", self.strPhone)
        print("Address: ", self.strAddress)

if __name__ == "__main__":
    pb1 = phonebook()
    pb1.setValue("Alice", "1234567890", "New York")
    pb1.display_phonebook()

    pb2 = phonebook()
    pb2.setValue("Bob", "9876543210", "Los Angeles")
    pb2.display_phonebook()

Name:  Alice
Phone:  1234567890
Address:  New York
Name:  Bob
Phone:  9876543210
Address:  Los Angeles


In [6]:
class phonebook:
    strName = ""
    strPhone = ""
    strAddress = ""

    def __init__(self, name, phone, address):
        self.strName = name
        self.strPhone = phone
        self.strAddress = address

    def setValue(self, name, phone, address):
        self.strName = name
        self.strPhone = phone
        self.strAddress = address

    def display_phonebook(self):
        print("Name: ", self.strName)
        print("Phone: ", self.strPhone)
        print("Address: ", self.strAddress)
       
if __name__ == "__main__":
    pb1 = phonebook("Alice", "1234567890", "New York")
    pb1.display_phonebook()

    pb2 = phonebook("Bob", "9876543210", "Los Angeles")
    pb2.display_phonebook()

Name:  Alice
Phone:  1234567890
Address:  New York
Name:  Bob
Phone:  9876543210
Address:  Los Angeles


In [7]:
listObjList = []
listObjList.append(pb1)
listObjList.append(pb2)
for obj in listObjList:
    obj.display_phonebook()

Name:  Alice
Phone:  1234567890
Address:  New York
Name:  Bob
Phone:  9876543210
Address:  Los Angeles


In [9]:
#Assignment 1: Create a class that represents a library and allows basic operations like checking availability and borrowing books.

# class attributes
# bookTitle(string)
# bookAuthor(string)
# available(boolean)

# Methods
# Constructor: sets class attributes for each book 
# borrow_book(): Changes the availability status to False if the book is available; otherwise, print"Not available"
# return_book(): Changes the availability status back to True
# display_info(): Prints the book's title, author, and avalability status

#Create two book objects (e.g. book1, book2) and demonstrate borrowing, returning, and displaying book information.

class library:
    bookTitle = ""
    bookAuthor = ""
    available = True

    def __init__(self, title, author):
        self.bookTitle = title
        self.bookAuthor = author

    def borrow_book(self):
        if self.available:
            self.available = False
        else:
            print("Not available")

    def return_book(self):
        self.available = True

    def display_info(self):
        print("Title: ", self.bookTitle)
        print("Author: ", self.bookAuthor)
        print("Available: ", self.available)

if __name__ == "__main__":
    book1 = library("Book1", "Author1")
    book1.borrow_book()
    book1.display_info()

    book2 = library("Book2", "Author2")
    book2.borrow_book()
    book2.display_info()

    book2.return_book()
    book2.display_info()
    

Title:  Book1
Author:  Author1
Available:  False
Title:  Book2
Author:  Author2
Available:  False
Title:  Book2
Author:  Author2
Available:  True


In [10]:
#Convert the following to instance variables 
# bookTitle (string)
# bookAuthor (me" string)
# availabe (boolean)

# Add a class variable "strLibraryName"


class library:
    strLibraryName = "My Library"

    def __init__(self, title, author):
        self.bookTitle = title
        self.bookAuthor = author
        self.available = True

    def borrow_book(self):
        if self.available:
            self.available = False
        else:
            print("Not available")

    def return_book(self):
        self.available = True

    def display_info(self):
        print("Library Name: ", library.strLibraryName)
        print("Title: ", self.bookTitle)
        print("Author: ", self.bookAuthor)
        print("Available: ", self.available)

if __name__ == "__main__":
    book1 = library("Book1", "Author1")
    book1.borrow_book()
    book1.display_info()

    book2 = library("Book2", "Author2")
    book2.borrow_book()
    book2.display_info()

    book2.return_book()
    book2.display_info()



Library Name:  My Library
Title:  Book1
Author:  Author1
Available:  False
Library Name:  My Library
Title:  Book2
Author:  Author2
Available:  False
Library Name:  My Library
Title:  Book2
Author:  Author2
Available:  True


In [11]:
# Create a class: clsSchool 
# Class variables:
#     school_name="Green Valley High School"  is a class variable that is common to all students. 
# Instance Variables: 
#     name
#     student_id 
#     maths_marks
#     science_Marks
#     english_marks
#     average

# Methods:
#     constructor which will initialize name,student_id and rest of attributes will be initialised to 0
#     add_marks(): Allows adding or updating marks for a specific subject 
#     calculate_average(): Calculate the average of all marks for a student and initializes the average variable
#     display_info(): Displays the student's details, marks,and avearge marks.



class clsSchool:
    school_name = "Green Valley High School"

    def __init__(self, name, student_id):
        self.name = name
        self.student_id = student_id
        self.maths_marks = 0
        self.science_marks = 0
        self.english_marks = 0
        self.average = 0

    def add_marks(self, subject, marks):
        if subject == "Maths":
            self.maths_marks = marks
        elif subject == "Science":
            self.science_marks = marks
        elif subject == "English":
            self.english_marks = marks

    def calculate_average(self):
        self.average = (self.maths_marks + self.science_marks + self.english_marks) / 3

    def display_info(self):
        print("School Name: ", clsSchool.school_name)
        print("Name: ", self.name)
        print("Student ID: ", self.student_id)
        print("Maths Marks: ", self.maths_marks)
        print("Science Marks: ", self.science_marks)
        print("English Marks: ", self.english_marks)
        print("Average Marks: ", self.average)

if __name__ == "__main__":
    student1 = clsSchool("Alice", 1)
    student1.add_marks("Maths", 90)
    student1.add_marks("Science", 85)
    student1.add_marks("English", 95)
    student1.calculate_average()
    student1.display_info()

    student2 = clsSchool("Bob", 2)
    student2.add_marks("Maths", 80)
    student2.add_marks("Science", 75)
    student2.add_marks("English", 85)
    student2.calculate_average()
    student2.display_info()

School Name:  Green Valley High School
Name:  Alice
Student ID:  1
Maths Marks:  90
Science Marks:  85
English Marks:  95
Average Marks:  90.0
School Name:  Green Valley High School
Name:  Bob
Student ID:  2
Maths Marks:  80
Science Marks:  75
English Marks:  85
Average Marks:  80.0


In [12]:
# Create a class: clsSchool 
# Class variables:
#     school_name="Green Valley High School"  is a class variable that is common to all students. 
# Instance Variables: 
#     name
#     student_id 
#     marks={maths:100,science:99,english:98,average}

# Methods:
#     constructor which will initialize name,student_id and rest of attributes will be initialised to 0
#     add_marks(): Allows adding or updating marks for a specific subject 
#     calculate_average(): Calculate the average of all marks for a student and initializes the average variable
#     display_info(): Displays the student's details, marks,and avearge marks.



# Challange: Display the name of the topper

class clsSchool:
    school_name = "Green Valley High School"

    def __init__(self, name, student_id):
        self.name = name
        self.student_id = student_id
        self.marks = {"Maths": 0, "Science": 0, "English": 0, "Average": 0}

    def add_marks(self, subject, marks):
        self.marks[subject] = marks

    def calculate_average(self):
        total = 0
        for subject, marks in self.marks.items():
            if subject != "Average":
                total += marks
        self.marks["Average"] = total / 3

    def display_info(self):
        print("School Name: ", clsSchool.school_name)
        print("Name: ", self.name)
        print("Student ID: ", self.student_id)
        for subject, marks in self.marks.items():
            print(f"{subject} Marks: {marks}")
        print("Average Marks: ", self.marks["Average"])

    def get_topper(self):
        topper = max(self.marks, key=self.marks.get)
        print(f"Topper: {topper}")

if __name__ == "__main__":
    student1 = clsSchool("Alice", 1)
    student1.add_marks("Maths", 90)
    student1.add_marks("Science", 85)
    student1.add_marks("English", 95)
    student1.calculate_average()
    student1.display_info()
    student1.get_topper()

    student2 = clsSchool("Bob", 2)
    student2.add_marks("Maths", 80)
    student2.add_marks("Science", 75)
    student2.add_marks("English", 85)
    student2.calculate_average()
    student2.display_info()
    student2.get_topper()



School Name:  Green Valley High School
Name:  Alice
Student ID:  1
Maths Marks: 90
Science Marks: 85
English Marks: 95
Average Marks: 90.0
Average Marks:  90.0
Topper: English
School Name:  Green Valley High School
Name:  Bob
Student ID:  2
Maths Marks: 80
Science Marks: 75
English Marks: 85
Average Marks: 80.0
Average Marks:  80.0
Topper: English


In [ ]:
# Assignment 1: Create a class that simulates a simple bank account and allows basic bank
# operations.
# Class Name: BankAccount
# Rate of interest
# Bank name
# * account_holder (string)
# * balance (float, initialized to 0.0)
# Methods:
# * deposit(amount): Adds the given amount to the balance.
# withdraw(amount): Deducts the given amount from the balance if sufficient funds are available;
# otherwise, print "insufficient balance.
# * check_balance(): Prints the current balance.
# Create an account for a user (e.g., account1 = BankAccount("Alice")), perform deposits,
# withdrawals, and check the balance.


class BankAccount:
    rate_of_interest = 5
    bank_name = "My Bank"

    def __init__(self, account_holder):
        self.account_holder = account_holder
        self.balance = 0.0

    def deposit(self, amount):
        self.balance += amount

    def withdraw(self, amount):
        if amount <= self.balance:
            self.balance -= amount
        else:
            print("Insufficient balance")

    def check_balance(self):
        print(f"Balance: {self.balance}")

if __name__ == "__main__":
    account1 = BankAccount("Alice")
    account1.deposit(1000)
    account1.check_balance()
    account1.withdraw(500)
    account1.check_balance()
    account1.withdraw(600)
    account1.check_balance()

    account2 = BankAccount("Bob")
    account2.deposit(2000)
    account2.check_balance()
    account2.withdraw(1500)
    account2.check_balance()
    account2.withdraw(1000)
    account2.check_balance()



# 10/10/2024

In [2]:
# inheritance 
# Base class (superclass)

class Animal:
    def __init__(self, name):
        self.name = name

    def speak(self):
        return f"{self.name} makes a sound"
    
class Dog(Animal):
    def speak(self):
        return f"{self.name} barks" 
    
class Cat(Animal):
    def speak(self):
        return f"{self.name} meows"
     
dog = Dog("Johnny")
cat = Cat("Elizabeth")

print(dog.speak())
print(cat.speak())



Johnny barks
Elizabeth meows


In [4]:
#Assognment 1: Calculate the area based on shape 
#create a parent class to ask for the shape
#create a subclass for calculating area of shape

class Shape:
    def __init__(self, shape):
        self.shape = shape

    def calculate_area(self):
        pass

class Circle(Shape):
    def __init__(self, shape, radius):
        super().__init__(shape)
        self.radius = radius

    def calculate_area(self):
        return 3.14 * self.radius * self.radius
    
class Rectangle(Shape):
    def __init__(self, shape, length, breadth):
        super().__init__(shape)
        self.length = length
        self.breadth = breadth

    def calculate_area(self):
        return self.length * self.breadth
    
shape = input("Enter the shape (Circle/Rectangle): ")
if shape == "Circle":
    radius = float(input("Enter the radius: "))
    circle = Circle(shape, radius)
    print(f"Area of the circle: {circle.calculate_area()}")
elif shape == "Rectangle":
    length = float(input("Enter the length: "))
    breadth = float(input("Enter the breadth: "))
    rectangle = Rectangle(shape, length, breadth)
    print(f"Area of the rectangle: {rectangle.calculate_area()}")
else:
    print("Invalid shape")





Area of the circle: 706.5


In [8]:
#Assognment 1: Calculate the area based on shape 
#create a parent class to ask for the shape
#create a subclass for calculating area of shape

# class shape: 
#     Attributes: shape_name=""
#     Method:
#     user_shape()
#     Ask user what shape to work with 

# class shape_area(shape):
#     Attributes: area
#     Method:
#     calculate_area()
#         based on shape, use if else statement to ask for radius /length from user. 
#         calculate area appropriately 
#     display_area()
#          print name of shape [use shape_name variable value form class shape]
#         print area

class shape:
    shape_name = ""

    def user_shape(self):
        self.shape_name = input("Enter the shape (Circle/Rectangle): ")

class shape_area(shape):
    area = 0

    def calculate_area(self):
        if self.shape_name == "Circle":
            radius = float(input("Enter the radius: "))
            self.area = 3.14 * radius * radius
        elif self.shape_name == "Rectangle":
            length = float(input("Enter the length: "))
            breadth = float(input("Enter the breadth: "))
            self.area = length * breadth

    def display_area(self):
        print(f"Shape: {self.shape_name}")
        print(f"Area: {self.area}")

shape1 = shape_area()
shape1.user_shape()
shape1.calculate_area()
shape1.display_area()


Shape: Circle
Area: 5024.0


In [1]:
class Animal:
    def __init__(self, name):
        print("Animal constructor")
        self.name = name

    def speak(self):
        return f"{self.name} makes a sound"
    
class Dog(Animal):
    def __init__(self, name, breed):
        print("Dog constructor")
        super().__init__(name)
        self.breed = breed

    def speak(self):
        return f"{self.name} barks"

class Cat(Animal):
    def __init__(self, name, color):
        print("Cat constructor")
        super().__init__(name)
        self.color = color

    def speak(self):
        return f"{self.name} meows"
    
dog = Dog("Johnny", "Labrador")
cat = Cat("Elizabeth", "White")


Dog constructor
Animal constructor
Cat constructor
Animal constructor


In [7]:
# Parent classs: Car 

# Attributes: 
# make(string): The make or brand of the car(e.g., Tesla,Toyota).
# model(string): The model of the car (e.g.,Model 3, Corolla)
# distance_traveled(float): The distance traveled by the car in kilometers

# Methods:
# calculate_mileage(): This will be overridden by the child classes to  calculate mileage using their respective formulas

class Car:
    def __init__(self, make, model):
        self.make = make
        self.model = model
        self.distance_traveled = 0.0

    def calculate_mileage(self):
        pass 

# Child Class: Electric_Vehicle(inherits from car)
# Additional Attribute:
#     energy_consumed(float): The energy consumed by the EV in kilowatt-hours(kWh)

# Method to Override: 
#     calculate_mileage():


# Formula: 
#     mileage(km/kWh) = distance_traveled/energy_consumed

#Without using super class method

class Electric_Vehicle(Car):
    def __init__(self, make, model, energy_consumed):
        self.energy_consumed = energy_consumed
        super().__init__(make, model)

    def calculate_mileage(self):
        return self.distance_traveled / self.energy_consumed
    

print("Electric Vehicle")
ev = Electric_Vehicle("Tesla", "Model 3", 100)
ev.distance_traveled = 200
print(ev.calculate_mileage())


# Child Class: Fuel_car(inherits from car)
# Additional Attribute:
#     fuel_consumed(float): The fuel consumed by the car in liters

# Method to Override:
#     calculate_mileage():

# Formula:
#     mileage(km/l) = distance_traveled/fuel_consumed

class Fuel_Car(Car):
    def __init__(self, make, model, fuel_consumed):
        self.fuel_consumed = fuel_consumed
        super().__init__(make, model)

    def calculate_mileage(self):
        return self.distance_traveled / self.fuel_consumed
print("Fuel Car")
fc = Fuel_Car("Toyota", "Corolla", 10)
fc.distance_traveled = 200
print(fc.calculate_mileage())

    






Electric Vehicle
2.0
Fuel Car
20.0


In [12]:
#Assignment 2: 
# Define Car class: 
#     it should initialize with the car's make,model, and distance traveled.
#     It should have a calculate_mileage() method. -print statement printing some random text 

# Define the Electric_Vehicle class that inherits from Car: 
# it should initialize with the car's make,model, distance traveled, and energy consumed.set
# get_car_details()

# Override the calculate_mileage() method to calculate the mileage using the formua for EVs.

# Define the Fuel_Car class that inherits from Car:
# It should initialize with the car's make,model, distance traveled,and fuel consumed.set
# override the calculate_mileage() method to calculate the mileage using the formula for fuel cars.
    
# write a script that:
# Creates one object for each type of car(Electric_Vehicle, Fuel_Car)
# Uses the calculate_mileage() method to print the mileage for both cars, demonstrating polymorphism.

class Car:
    def __init__(self, make, model, distance_traveled):
        self.make = make
        self.model = model
        self.distance_traveled = distance_traveled

    def calculate_mileage(self):
        print("Random text")

class Electric_Vehicle(Car):
    def __init__(self, make, model, distance_traveled, energy_consumed):
        self.energy_consumed = energy_consumed
        super().__init__(make, model, distance_traveled)

    def calculate_mileage(self):
        return self.distance_traveled / self.energy_consumed
    
class Fuel_Car(Car):
    def __init__(self, make, model, distance_traveled, fuel_consumed):
        self.fuel_consumed = fuel_consumed
        super().__init__(make, model, distance_traveled)

    def calculate_mileage(self):
        return self.distance_traveled / self.fuel_consumed
    
ev = Electric_Vehicle("Tesla", "Model 3", 200, 100)
print("milage for EV: ", ev.calculate_mileage())

fc = Fuel_Car("Toyota", "Corolla", 200, 10)
print("milage for FC: ", fc.calculate_mileage())



milage for EV:  2.0
milage for FC:  20.0


In [13]:
class Car:
    def __init__(self, make, model, distance_traveled):
        self.make = make
        self.model = model
        self.distance_traveled = distance_traveled

    def calculate_mileage(self):
        print("Random text")

class Electric_Vehicle(Car):
    def __init__(self, make, model, distance_traveled, energy_consumed):
        self.energy_consumed = energy_consumed
        self.model = model
        self.distance_traveled = distance_traveled


    def calculate_mileage(self):
        return self.distance_traveled / self.energy_consumed
    
class Fuel_Car(Car):
    def __init__(self, make, model, distance_traveled, fuel_consumed):
        self.fuel_consumed = fuel_consumed
        self.model = model
        self.distance_traveled = distance_traveled


    def calculate_mileage(self):
        return self.distance_traveled / self.fuel_consumed
    
ev = Electric_Vehicle("Tesla", "Model 3", 200, 100)
print("milage for EV: ", ev.calculate_mileage())

fc = Fuel_Car("Toyota", "Corolla", 200, 10)
print("milage for FC: ", fc.calculate_mileage())


milage for EV:  2.0
milage for FC:  20.0


In [21]:
#Class parent_A 
#Attributes: num1,num2 
# Method: 
#     __init__: to get values of numbers
#     math_operation(): add both numbers, print result
# #Class child_B 
# Method: 
# math_operation(): multiply both numbers, print result
# use super() keyword to add both numbrs


class parent_A:
    def __init__(self, num1, num2):
        self.num1 = num1
        self.num2 = num2

    def math_operation(self):
        result = self.num1 + self.num2
        print(f"Addition result: {result}")

class child_B(parent_A):
    def math_operation(self):
        super().math_operation()
        result = self.num1 * self.num2
        print(f"Multiplication result: {result}")


b = child_B(3, 5)
b.math_operation()


Addition result: 8
Multiplication result: 15


# 11/10/24

In [ ]:
class car:
    def __init__(self, make, model):
        self.make = make
        self.model = model
        self.year = year 

    def display_info(self):
        return f"{self.make} {self.model}, Year: {self.year}"
        def get_year(self):
            return self.year
        
        my_car = car("Toyota", "Corolla" 2020)
        print(my_car.display_info())

        my_car.year = (1999)
        print(my_car.display_info())


In [3]:
# class parent_A
# Attribute : private class variables : num1,num2
# method :
# __init__ : to get values of numbers
# math_operations() : add both numbers, print result

# class child_B
# method :
# math_operaton() : multiply both numbers, print result
# use super() keyword to add both numbers

class parent_A:
    def __init__(self, num1, num2):
        self.__num1 = num1
        self.__num2 = num2

    def math_operation(self):
        result = self.__num1 + self.__num2
        print(f"Addition result: {result}")

class child_B(parent_A):
    def math_operation(self):
        super().math_operation()
        result = self._parent_A__num1 * self._parent_A__num2
        print(f"Multiplication result: {result}")

b = child_B(3, 5)
b.math_operation()  


Addition result: 8
Multiplication result: 15


In [9]:
#Assignmnt 2 
# Add 2 protected integer variables in parent_A 
# Initialize them to some integer values 
# Multiply them inside the method math_operation() form child_B 

class parent_A:
    def __init__(self, num1, num2):
        self.__num1 = num1
        self.__num2 = num2
        self._num3 = 10
        self._num4 = 20

    def math_operation(self):
        result = self.__num1 + self.__num2
        print(f"Addition result: {result}")

class child_B(parent_A):

    def math_operation(self):
        super().math_operation()
        result = self._num3 * self._num4
        print(f"Multiplication result: {result}")
        #print(f"Accessing protected variables: {self._num3} and {self._num4}")
        #print(f"Accessing private variables: {self._parent_A__num1} and {self._parent_A__num2}")

b = child_B(3, 5)
b.math_operation()



Addition result: 8
Multiplication result: 200


In [1]:
# # Assignment 3: 
# Add 2 public integer variabes in parent_A
# Initialize them to some integer values 
# Multiply them inside the metthod math_operation() from child_B
# multiply them from outside the methods of class.

class parent_A:
    def __init__(self, num1, num2):
        self.__num1 = num1
        self.__num2 = num2
        self._num3 = 10
        self._num4 = 20
        self.num5 = 30
        self.num6 = 40

    def math_operation(self):
        result = self.__num1 + self.__num2
        print(f"Addition result: {result}")

class child_B(parent_A):
    def math_operation(self):
        super().math_operation()
        result = self._num3 * self._num4
        print(f"Multiplication result: {result}")

b = child_B(3, 5)
b.math_operation()
result = b.num5 * b.num6
print(f"Multiplication result: {result}")




Addition result: 8
Multiplication result: 200
Multiplication result: 1200


In [3]:
form abc import ABC, abstractmethod
class Animal(ABC):
    @abstractmethod
    def speak(self):
        pass

class Dog(Animal):
    def speak(self):
        return "Dog barks"
    
    class Cat(Animal):
        def speak(self):
            return "Cat meows"
            
dog = Dog()
print(dog.speak())
cat = Cat()
print(cat.speak())


SyntaxError: invalid syntax (2771803689.py, line 1)

In [9]:
class Animal:
    def speak(self):
        print("Animal speaks")  

class Mammal(Animal):
    def speak(self):
        print("Mammal speaks")

class Dog(Mammal):
    def speak(self):
        print("Dog barks")


dog = Dog()
dog.speak()


Dog barks


In [13]:
class Dog(Animal):
    def __init__(self, name):
        self.name = name

    def speak(self):
        return f"{self.name} barks"
    
class Cat(Animal):
    def __init__(self, name):
        self.name = name

    def speak(self):
        return f"{self.name} meows"
    
class Bird(Animal):
    def __init__(self, name):
        self.name = name

    def speak(self):
        return f"{self.name} chirps"
    
dog = Dog("buddy")
cat = Cat("kitty")
bird = Bird("tweetie")

print(dog.speak())
print(cat.speak())
print(bird.speak())

buddy barks
kitty meows
tweetie chirps


In [1]:
# Assignmet 4: Use abstract classes to manage a vehicle system and enforce method implementation acress various vehicle types. 

# Tasks. 
# Create an abstract class Vehicle  with the following abstract methods:
#     start(): to start the vehicle 
#     stop(): to stop the vehicle

# Implement three subclasses: Car,Bike,and Bus, each with custom implementations for start() and stop().count

# Create a Garage class that can add vehicles and call their start() and stop() methods. 

# Demonstrate adding different vehicles type to the garbage and operating them.

from abc import ABC, abstractmethod

class Vehicle(ABC):
    @abstractmethod
    def start(self):
        pass

    @abstractmethod
    def stop(self):
        pass

class Car(Vehicle):
    def start(self):
        print("Car started")

    def stop(self):
        print("Car stopped")

class Bike(Vehicle):
    def start(self):
        print("Bike started")

    def stop(self):
        print("Bike stopped")

class Bus(Vehicle):
    def start(self):
        print("Bus started")

    def stop(self):
        print("Bus stopped")

#class Garage:
    def __init__(self):
        self.vehicles = []

    def add_vehicle(self, vehicle):
        self.vehicles.append(vehicle)

    def operate_vehicles(self):
        for vehicle in self.vehicles:
            vehicle.start()
            vehicle.stop()

#garage = Garage()
car = Car()
bike = Bike()
bus = Bus()
# garage.add_vehicle(car)
# garage.add_vehicle(bike)
# garage.add_vehicle(bus)
#garage.operate_vehicles()



In [8]:
#Class GusetUser (inherits form user):
# Guests can add items to the cart but cannot processed to checkout. 
# Class RegisterdUser (inherits from user):
# Additional Attribute:
#     address(string)

# Methods:
#     checkout: Allow the user to processed to checkout by printing the final totol and deducting the product stock


class User:
    def __init__(self, name):
        self.name = name
            
    def add_to_cart(self, item):
        print(f"{self.name} added {item} to the cart")

class GuestUser(User):
    def __init__(self, name):
        super().__init__(name)
            
    def checkout(self):
        print("Guest user cannot checkout")

class RegisteredUser(User):
    def __init__(self, name, address):
        super().__init__(name)
        self.address = address
            
    def checkout(self, total):
        print(f"{self.name} checked out. Final total: {total}")

guest = GuestUser("Guest")
guest.add_to_cart("item1")
guest.checkout()

registered = RegisteredUser("RegisteredUser", "123 Main St")
registered.add_to_cart("item2")
registered.checkout(100)





Guest added item1 to the cart
Guest user cannot checkout
RegisteredUser added item2 to the cart
RegisteredUser checked out. Final total: 100


In [9]:
#Class Product: 
# Attributes: 
#     Class variable: Product_list 
#     {name: {price:12,qty:20,country_of_origin:"india"}}
#     Inatance variables: 
#     name(string)
#     price(float)
#     stock(integer)-the quantitiy of the product available 
#     country_of_origin(string)

# Method: 
# __init__: initialize the product attributes and add to dictionary. 
# get_details: Return the product details in dictionary format.

class Product:
    Product_list = {}

    def __init__(self, name, price, stock, country_of_origin):
        self.name = name
        self.price = price
        self.stock = stock
        self.country_of_origin = country_of_origin
        Product.Product_list[name] = {"price": price, "qty": stock, "country_of_origin": country_of_origin}

    def get_details(self):
        return Product.Product_list[self.name]
    
product1 = Product("item1", 10, 20, "India")
print(product1.get_details())



{'price': 10, 'qty': 20, 'country_of_origin': 'India'}


In [16]:
# #Assignment 6:Build an online shoppin system 
# operations: 
# create procuct instances (stored in a dictionary).
# allow a user( either guest or registered) to:
#     view products. 
#     add products to the cart(ensure sufficient stock).
#     View the cart and total price. 
#     if the user is registered, they should be able to processed to checkout, reducing the stock of purchased products

class Product:
    Product_list = {}

    def __init__(self, name, price, stock, country_of_origin):
        self.name = name
        self.price = price
        self.stock = stock
        self.country_of_origin = country_of_origin
        Product.Product_list[name] = {"price": price, "qty": stock, "country_of_origin": country_of_origin}

    def get_details(self):
        return Product.Product_list[self.name]
    
class User:
    def __init__(self, name):
        self.name = name
        self.cart = {}

    def view_products(self):
        return Product.Product_list

    def add_to_cart(self, product, qty):
        if product in self.cart:
            self.cart[product] += qty
        else:
            self.cart[product] = qty

    def view_cart(self):
        return self.cart
    
    def view_total(self):
        total = 0
        for product, qty in self.cart.items():
            total += Product.Product_list[product]["price"] * qty
        return total
    
class GuestUser(User):
    def __init__(self, name):
        super().__init__(name)
            
    def checkout(self):
        print("Guest user cannot checkout")

class RegisteredUser(User):

    def __init__(self, name, address):
        super().__init__(name)
        self.address = address
            
    def checkout(self):
        for product, qty in self.cart.items():
            Product.Product_list[product]["qty"] -= qty
        print(f"{self.name} checked out. Final total: {self.view_total()}")

product1 = Product("item1", 10, 20, "India")

user = User("User")
print(user.view_products())

user.add_to_cart("item1", 2)
print(user.view_cart())
print(user.view_total())

guest = GuestUser("Guest")
guest.add_to_cart("item1", 3)
print(guest.view_cart())
print(guest.view_total())
guest.checkout()

registered = RegisteredUser("RegisteredUser", "123 Main St")
registered.add_to_cart("item1", 4)
print(registered.view_cart())
print(registered.view_total())
registered.checkout()
print(Product.Product_list)


    

{'item1': {'price': 10, 'qty': 20, 'country_of_origin': 'India'}}
{'item1': 2}
20
{'item1': 3}
30
Guest user cannot checkout
{'item1': 4}
40
RegisteredUser checked out. Final total: 40
{'item1': {'price': 10, 'qty': 16, 'country_of_origin': 'India'}}


In [17]:
# Class GuestUser (inherits from User):
# Guests can add items to the cart but cannot processed to checkout. 

# Class RegisteredUser (inherits from User):
# Additional Attribute: 
#     address(string)

# Methods:
#     checkout: Allow the user to processed to checkout by printing the final total and deducting the product stock

class User:
    def __init__(self, name):
        self.name = name

    def add_to_cart(self, item):
        print(f"{self.name} added {item} to the cart")

class GuestUser(User):
    def __init__(self, name):
        super().__init__(name)

    def checkout(self):
        print("Guest user cannot checkout")

class RegisteredUser(User):
    def __init__(self, name, address):
        super().__init__(name)
        self.address = address

    def checkout(self, total):
        print(f"{self.name} checked out. Final total: {total}")


guest = GuestUser("Guest")
guest.add_to_cart("item1")
guest.checkout()

registered = RegisteredUser("RegisteredUser", "123 Main St")
registered.add_to_cart("item2")
registered.checkout(100)



Guest added item1 to the cart
Guest user cannot checkout
RegisteredUser added item2 to the cart
RegisteredUser checked out. Final total: 100


In [20]:
# Challange:
# Read contents of products form a csv file .Populate dictionary of products using these details. sample csv file: 

# name,price,qty,origin
# item1,10,20,India
# item2,20,30,USA
# item3,30,40,China

# filename:data.csv


import csv

class Product:
    Product_list = {}

    def __init__(self, name, price, stock, country_of_origin):
        self.name = name
        self.price = price
        self.stock = stock
        self.country_of_origin = country_of_origin
        Product.Product_list[name] = {"price": price, "qty": stock, "country_of_origin": country_of_origin}

    def get_details(self):
        return Product.Product_list[self.name]
    
class User:
    def __init__(self, name):
        self.name = name
        self.cart = {}

    def view_products(self):
        return Product.Product_list

    def add_to_cart(self, product, qty):
        if product in self.cart:
            self.cart[product] += qty
        else:
            self.cart[product] = qty

    def view_cart(self):
        return self.cart
    
    def view_total(self):
        total = 0
        for product, qty in self.cart.items():
            total += Product.Product_list[product]["price"] * qty
        return total
    
class GuestUser(User):
    def __init__(self, name):
        super().__init__(name)
            
    def checkout(self):
        print("Guest user cannot checkout")

class RegisteredUser(User):
    
        def __init__(self, name, address):
            super().__init__(name)
            self.address = address
                
        def checkout(self):
            for product, qty in self.cart.items():
                Product.Product_list[product]["qty"] -= qty
            print(f"{self.name} checked out. Final total: {self.view_total()}")

with open("data.csv") as file:
    reader = csv.reader(file)
    next(reader)  # Skip the header row
    for row in reader:
        if row[0] != "name":  # Ensure we skip any header row
            product = Product(row[0], float(row[1]), int(row[2]), row[3])

user = User("User")
print(user.view_products())

user.add_to_cart("item1", 2)
print(user.view_cart())
print(user.view_total())

guest = GuestUser("Guest")
guest.add_to_cart("item1", 3)
print(guest.view_cart())
print(guest.view_total())
guest.checkout()


registered = RegisteredUser("RegisteredUser", "123 Main St")
registered.add_to_cart("item1", 4)
print(registered.view_cart())
print(registered.view_total())
registered.checkout()
print(Product.Product_list)





{'item1': {'price': 10.0, 'qty': 20, 'country_of_origin': 'India'}, 'item2': {'price': 20.0, 'qty': 30, 'country_of_origin': 'USA'}, 'item3': {'price': 30.0, 'qty': 40, 'country_of_origin': 'China'}}
{'item1': 2}
20.0
{'item1': 3}
30.0
Guest user cannot checkout
{'item1': 4}
40.0
RegisteredUser checked out. Final total: 40.0
{'item1': {'price': 10.0, 'qty': 16, 'country_of_origin': 'India'}, 'item2': {'price': 20.0, 'qty': 30, 'country_of_origin': 'USA'}, 'item3': {'price': 30.0, 'qty': 40, 'country_of_origin': 'China'}}


In [1]:
# #12/10/2024
# Basic syntax - Metachaaracters
# . - Any character except newline
# ^ - Starts with
# $ - Ends with
# * - Zero or more occurrences
# + - One or more occurrences
# ? - Zero or one occurrence
# {} - Exactly the specified number of occurrences
# [] - A set of characters
# | - Either or
# () - Capture and group

In [2]:
#Example:

import re

txt = "The rain in Spain"
x = re.search("^The.*Spain$", txt)
if x:
    print("Yes, we have a match!")
else:
    print("No match")

#Assignment 1:
# Write a Python program to check that a string contains only a certain set of characters (in this case a-z, A-Z and 0-9).

import re

def check_string(s):
    return bool(re.match("^[a-zA-Z0-9]*$", s))



Yes, we have a match!


In [3]:
#[a-z]: Any lowercase letter
#[A-Z]: Any uppercase letter
#[0-9]: Any digit
#\d: Any digit
#\D: Any non-digit
#\w: Any alphanumeric character
#\W: Any non-alphanumeric character
#\s: Any whitespace
#\S: Any non-whitespace



In [4]:
#Write a function find_start_with_lowercase(strings) that takes a list of strings and returns all the strings that start with a lowercase letter(a-z).

import re

def find_start_with_lowercase(strings):
    return [s for s in strings if re.match("^[a-z]", s)]

strings = ["apple", "Banana", "cherry", "date", "Eggplant"]
print(find_start_with_lowercase(strings))



['apple', 'cherry', 'date']


In [6]:
#Write a function find_lowercase_substrings(strings) that takes a list of strings and returns all the substrings that contain only lowercase alphabetic characters, using[a-z]. pattern.

import re

def find_lowercase_substrings(strings):
    return [s for s in strings if re.match("^[a-z]*$", s)]

strings = ["apple", "Banana", "cherry", "date", "Eggplant"]
print(find_lowercase_substrings(strings))



['apple', 'cherry', 'date']


In [8]:
import re

def find_lowercase_substrings(strings):
    return [s for s in strings if re.match("[a-z]+", s)]

strings = ["apple", "Banana", "cherry", "date", "Eggplant"]
print(find_lowercase_substrings(strings))



['apple', 'cherry', 'date']


In [9]:
#Assignment Write the function find_exact_repetitions(strings, pattern, n): 

# This function should loop through each string in the list and use a regular expression pattern to find sequences where the given pattern is repeated exactly n times

# input: ["hello", "hoooray","aaaaaa","123456","boooom"]
# n:3
# Pattern:'o'


import re

def find_exact_repetitions(strings, pattern, n):
    return [s for s in strings if re.search(f"{pattern}{{{n}}}", s)]

strings = ["hello", "hoooray", "aaaaaa", "123456", "boooom"]
pattern = "o"

print(find_exact_repetitions(strings, pattern, 3))

#use pattern "o{3}" to find the strings where the letter 'o' is repeated exactly 3 time



['hoooray', 'boooom']


In [19]:
# Assignment 7: Read a file and print lines which begin with "Start" and ends with "End"

# Sample Content for .txt file: 


# start 1st line End 
# start 2nd line
# start 3rd line End
# 4th line end


import re

with open("data.txt") as file:
    for line in file:
        line = line.strip()
        if re.match("^Start.*End$", line):
            print(line)




Start 1st line End
Start 3rd line End


In [17]:
# Assignment 7: Read a file and print lines which begin with "Start" and ends with "End"

# Sample Content for .txt file: 


# start 1st line End 
# start 2nd line
# start 3rd line End
# 4th line end




import re
def filter_lines(filename): 
    pattern = r"^Start.*End$"
    with open(filename, "r") as file:
        for line in file:
            line=line.strip()
            if re.match(pattern, line):
                print(line)

filter_lines("data.txt")



Start 1st line End
Start 3rd line End


In [49]:
# Assignmnet 8: Read a file and perform following operations on it: 
# Task 1: Find and print all words that start with a  vowel (a,e,i,o,u) and end with a consonant(b,c,d,f,g,h,j,k,l,m,n,p,q,r,s,t,v,w,x,y,z).

# Task 2: Extract and print all sequences of digits that are followed by a non-digit charactrer. 

# Task 3: Identify and print all lines that start with the word "Note" and end with an exclamation mark.(!)

# Contents of file: 
# Here are some examples: 
    # Apple pie is delicious
    # Under the bed, there is a cat! 
    # Notes from the metting!
    # 1234a5678b89aaa
    # Do not forget to check the details!

import re

def process_file(filename):
    with open(filename, "r") as file:
        for line in file:
            line = line.strip()
            # Task 1
            #print(re.findall(r"\b[aeiouAEIOU][a-zA-Z]*[b-df-hj-np-tv-z]\b", line))
            if re.match(r"\b[aeiouAEIOU][a-zA-Z]*[b-df-hj-np-tv-z]\b", line):
                print(line)
            
            # Task 2
            #print(re.findall(r"\d+(?=\D)", line))
            # if re.findall(r"\d+(?=\D)", line):
            #     print(line)

            # using [\d] + [^\d] to find the sequences of digits that are followed by a non-digit character
            digit_sequences = re.findall(r"\d+\D", line)
            for seq in digit_sequences:
                print(seq,end="")

                        
                        
                
            # Task 3
            #print(re.findall(r"^Note.*!$", line))
            if re.match(r"^Note.*!$", line):
                print(line)

process_file("data1.txt")



Under the bed, there is a cat!
Notes from the metting!
1234a5678b89a

In [51]:
import numpy as np

array = np.array([1, 2, 3, 4, 5])
print("1D Array :", array)

array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array: ", array_2d)

array_3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print("3D Array: ", array_3d)

zeros = np.zeros((2, 3))
print("Zeros Array: ", zeros)

ones = np.ones((2, 3))
print("Ones Array: ", ones)

full_array = np.full((2, 3), 5)
print("Full Array: ", full_array)

range_array = np.arange(0, 10, 2)
print("Range Array: ", range_array)

step_array = np.linspace(0, 10, 6)
print("Step Array: ", step_array)


1D Array : [1 2 3 4 5]
2D Array:  [[1 2 3]
 [4 5 6]]
3D Array:  [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Zeros Array:  [[0. 0. 0.]
 [0. 0. 0.]]
Ones Array:  [[1. 1. 1.]
 [1. 1. 1.]]
Full Array:  [[5 5 5]
 [5 5 5]]
Range Array:  [0 2 4 6 8]
Step Array:  [ 0.  2.  4.  6.  8. 10.]


In [52]:
#assignment 1: Create a 1 D Numpy array with 20 elements, ranging form 0 to 19. usning np.arange() method.


import numpy as np

array = np.arange(20)
print(array)



[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [53]:
#assignment 2: reshape the 1D array into a 4*5 2D array. Flatten the 4*5 2D array 

import numpy as np

array = np.arange(20).reshape(4, 5)
print(array)

flattened_array = array.flatten()
print(flattened_array)



[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [56]:
#assignment 3: Create a 3*3 matrix of random integers between 1 to 10. using np.random.randint() method.Transpose the 3*3 random integer matrix.

import numpy as np

matrix = np.random.randint(1, 10, (3, 3))
print(matrix)

transposed_matrix=np.transpose(matrix)
print(transposed_matrix)
# transposed_matrix = matrix.T
# print(transposed_matrix)


[[9 7 6]
 [3 6 4]
 [3 8 6]]
[[9 3 3]
 [7 6 8]
 [6 4 6]]


In [57]:
#write a program  to multipy all the  items in a list.

def multiply_list(items):
    result = 1
    for item in items:
        result *= item
    return result

items = [1, 2, 3, 4, 5]
print(multiply_list(items))



120


In [59]:
#write a program to get the smallest number from a list.

def get_smallest_number(items):
    smallest = items[0]
    for item in items:
        if item < smallest:
            smallest = item
    return smallest

items = [5, 2, 3, 4, 1]
print(get_smallest_number(items))



1


In [62]:
#using min function to get the smallest number from a list.

items = [5, 2, 3, 4, 1]
print(min(items))



1


In [66]:
#define a fuction overlapping() that  takes two lists and returns True if they have at least one member in common, False otherwise.

def overlapping(list1, list2):
    for item in list1:
        if item in list2:
            return True
    return False

# Example usage
list1 = [1, 2, 3, 4, 5]
list2 = [5, 6, 7, 8, 9]
print(overlapping(list1, list2))  # Output: True







True


In [67]:
#write  a fumcton find_longest_word() that takes a list of words and returns the length of the longest one.

def find_longest_word(words):
    longest = 0
    for word in words:
        if len(word) > longest:
            longest = len(word)
    return longest

words = ["apple", "banana", "cherry"]
print(find_longest_word(words))



6


In [69]:
# create a tuple, print  that tuple.
# insert/delete an item in tuple.

tuple = (1, 2, 3, 4, 5)
print(tuple)

# Insert an item
tuple = tuple + (6,)
print(tuple)

# Delete an item
tuple = tuple[:2] + tuple[3:]
print(tuple)



(1, 2, 3, 4, 5)
(1, 2, 3, 4, 5, 6)
(1, 2, 4, 5, 6)


In [72]:
#Accept name, address, email, bithedate(dd/mm/yyyy),phone no (list) and store these details in a dictionary.

name = input("Enter name: ")
address = input("Enter address: ")
email = input("Enter email: ")
birthdate = input("Enter birthdate (dd/mm/yyyy): ")
phone = input("Enter phone numbers (comma separated): ").split(",")
details = {
    "name": name,
    "address": address,
    "email": email,
    "birthdate": birthdate,
    "phone": phone
}
print(details)

{'name': '', 'address': '', 'email': '', 'birthdate': '', 'phone': ['']}


In [73]:
#Accept  more such details and add to a list to form a list of dictionaries.

details_list = []
for _ in range(3):
    name = input("Enter name: ")
    address = input("Enter address: ")
    email = input("Enter email: ")
    birthdate = input("Enter birthdate (dd/mm/yyyy): ")
    phone = input("Enter phone numbers (comma separated): ").split(",")
    details = {
        "name": name,
        "address": address,
        "email": email,
        "birthdate": birthdate,
        "phone": phone
    }
    details_list.append(details)
print(details_list)




[{'name': '', 'address': '', 'email': '', 'birthdate': '', 'phone': ['']}, {'name': '', 'address': '', 'email': '', 'birthdate': '', 'phone': ['']}, {'name': '', 'address': '', 'email': '', 'birthdate': '', 'phone': ['']}]


In [74]:
# create a .txt file.buffer
# open file in read mode.
# print everything written in a file.
# print  count of total no of lines in the file.
# print total no of words in the file.

with open("data.txt", "w") as file:
    file.write("Hello, World!\n")
    file.write("This is a test file.\n")
    file.write("It contains three lines.\n")

with open("data.txt", "r") as file:
    content = file.read()
    print(content)

    file.seek(0)
    lines = file.readlines()
    print(len(lines))

    words = content.split()
    print(len(words))





Hello, World!
This is a test file.
It contains three lines.

3
11


In [1]:
# Assignment 2: Masking PII (Personal Identifiable Information)

# *> Implement a function mask_sensitive_info(info,info_type) that takes two parameters: 
#     string: The string containing the sensitive information. 
#     string_type:A string indicating the type of information. It can be "email" or "credit_card".
#     Email:Mask the characters in the local part of the email (before the @ symbol) except the first and last character.
#     "Mayura.Kumari@xyz.com" should become "m**i@xyz.com"
#     credit card: Mask all but the last four digits of the credit card number. 
#     "1234 5678 9101 1121" should become "************1121"

# *> Exception Handling: 
#     If the info_type is not recognized, raise a ValueError with the message "Invalid info type". Handle more exceptions for cases such as incorrect formatting of the input information.
def mask_sensitive_info(info, info_type):
    if info_type == "email":
        if "@" not in info or info.count("@") != 1:
            raise ValueError("Invalid email format")
        local_part, domain = info.split("@")
        masked_local_part = local_part[0] + "*" * (len(local_part) - 2) + local_part[-1]
        return masked_local_part + "@" + domain
    elif info_type == "credit_card":
        card_number = info.replace(" ", "")
        if not card_number.isdigit() or len(card_number) < 4:
            raise ValueError("Invalid credit card format")
        masked_card_number = "*" * (len(card_number) - 4) + card_number[-4:]
        return masked_card_number
    else:
        raise ValueError("Invalid info type")

email = "gauravchaudhari@gmail.com"
info = "1234 5678 9101 1121"

try:
    masked_email = mask_sensitive_info(email, "email")
    print(masked_email)
except ValueError as e:
    print(e)

try:
    masked_credit_card = mask_sensitive_info(info, "credit_card")
    print(masked_credit_card)
except ValueError as e:
    print(e)



g*************i@gmail.com
************1121


In [3]:
#Assinment 3 Reverse a given list in python 
#E.g. aList = [100, 200, 300, 400, 500] output:[ 500, 400, 300, 200, 100]

aList = [100, 200, 300, 400, 500]
aList.reverse()
print(aList)


[500, 400, 300, 200, 100]


In [6]:
#Assignment 4: Find the larger and smallest number in the list which taken as input form user using list operations.    
numbers = []
input_numbers = input("Enter numbers: ")
for x in input_numbers.split():
    numbers.append(int(x))
largest = max(numbers)
smallest = min(numbers)
print(f"Largest: {largest}, Smallest: {smallest}")


Largest: 66, Smallest: 1


In [7]:
# Assignment 5: Music Manager

# Initialize an empty list playlist to sotre song titles(strings)

# Implement the following operations as separate functions: 
#     Add songs: Prompt user to ener song titles(comma-separated) add them to list
#     Remove song: Prompt user for a song title and remove it from list if it exists. 
#     View all songs: Display all songs in playlist, join them into a single string. 
#     Slice playlist: Prompt user for start and end indices to display a sliced protion of the playlist 


# Add exception handling, Identify possible excaption conditions

playlist = []

def add_songs():
    songs = input("Enter song titles (comma-separated): ").split(",")
    playlist.extend(songs)

def remove_song():
    song = input("Enter song title to remove: ")
    if song in playlist:
        playlist.remove(song)
    else:
        print("Song not found")

def view_all_songs():
    print(", ".join(playlist))

def slice_playlist():
    start = int(input("Enter start index: "))
    end = int(input("Enter end index: "))
    print(playlist[start:end])

while True:
    print("1. Add songs")
    print("2. Remove song")
    print("3. View all songs")
    print("4. Slice playlist")
    print("5. Exit")
    choice = int(input("Enter choice: "))
    if choice == 1:
        add_songs()
    elif choice == 2:
        remove_song()
    elif choice == 3:
        view_all_songs()
    elif choice == 4:
        slice_playlist()
    elif choice == 5:
        break
    else:
        print("Invalid choice")


        

1. Add songs
2. Remove song
3. View all songs
4. Slice playlist
5. Exit
1. Add songs
2. Remove song
3. View all songs
4. Slice playlist
5. Exit
hi,  hello
1. Add songs
2. Remove song
3. View all songs
4. Slice playlist
5. Exit
1. Add songs
2. Remove song
3. View all songs
4. Slice playlist
5. Exit
 hello
1. Add songs
2. Remove song
3. View all songs
4. Slice playlist
5. Exit
 hello
1. Add songs
2. Remove song
3. View all songs
4. Slice playlist
5. Exit


In [9]:
# create  a tuple namesd shopping_cart that continbs the following items:'laptop','headphones','keyboard','mouse'.
# print the shopping_cart tuple.
# access and print  the item in the shopping_cart.
# access and print the first 3 items in the shopping_cart.
# concatenate the shopping_cart tuple with another tuple containing the items 'monitor' and 'printer'. print the result.
# unpack the shopping_cart tuple into four variables : item1,item2,item3,item4. print the variables.
# print the variables to verify the unpacking. 

# use the .count() method to method to find the index of 'keyboard' in the tuple.

shopping_cart = ('laptop', 'headphones', 'keyboard', 'mouse'),
print(shopping_cart)

# Access and print the item in the shopping_cart
print(shopping_cart[2])

# Access and print the first 3 items in the shopping_cart
print(shopping_cart[:3])

# Concatenate the shopping_cart tuple with another tuple containing the items 'monitor' and 'printer'
new_items = ('monitor', 'printer')
shopping_cart = shopping_cart + new_items
print(shopping_cart)

# Unpack the shopping_cart tuple into four variables: item1, item2, item3, item4
item1, item2, item3, item4, item5, item6 = shopping_cart
print(item1, item2, item3, item4)

# Use the .index() method to find the index of 'keyboard' in the tuple
print(shopping_cart.index('keyboard'))




('laptop', 'headphones', 'keyboard', 'mouse')
keyboard
('laptop', 'headphones', 'keyboard')
('laptop', 'headphones', 'keyboard', 'mouse', 'monitor', 'printer')
laptop headphones keyboard mouse
2
